### ISSUE TITLE
Creacion de repositorio necesidades CRUD y generacion de API de acuerdo a lineamientos ajustando el modelo a los requerimientos actuales

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_crud#13]
- [x] creacion del api crud de necesidades

**Comment by CarlosGutierrezArdila** [comment]
tarea terminada 100% y lista para revision

**Comment by Soulfilip-UD** [comment]
Url del repositorio https://github.com/udistrital/necesidades_crud/

todo perfecto 💯 💯 

Proceeding to close Issue 👾
