### ISSUE TITLE
Incluir Beego Migrations con inserción de datos para API de necesidades CRUD

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_crud#14]
- [x] migraciones para estructura de esquemas y tablas

- [x] migraciones para datos de prueba

**Comment by CarlosGutierrezArdila** [comment]
32a445386cccaf54dd118ab1117519f14f83fd8b

**Comment by CarlosGutierrezArdila** [comment]
Se termina la tarea 100% para revision LT @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Todo perfecto muy buena 👍  , se evidencian migraciones desde la bd

Proceeding to close issue 👾
