### ISSUE TITLE
Ajustar modelo de fuentes vs Actividades frente a reunion 23/10/2019

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_crud#15]
- [x] incluir relación de fuentes con actividades

**Comment by CarlosGutierrezArdila** [comment]
e17c0cd36590b324d2260c6eef6e0debe0442064

**Comment by CarlosGutierrezArdila** [comment]
Tarea finalizada para revision LT @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Todo perfecto pruebas realizadas y desplegadas en test 

Proceeding to close Issue 👾
