### ISSUE TITLE
Pruebas unitarias: necesidades CRUD

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/necesidades_crud#19]
Realizar pruebas unitarias para los endpoints relacionados a la necesidad

**Comment by miguelramirez93** [comment]
Se realiza una generalizacón de los test CRUD de beego , ya que las estructuras son diferntes para cada tabla, solo se debe definir el objeto en cada test y su actualizacion, el componente de test se encargar de revisar las operaciones CRUD sobre estos. se añadio ejemplo de prueba en tipo_contrato_necesidad. Se aclara que como no se conoce la estructura de la DB en su totalidad se hizo el esfuerzo de generalizar para que los responsables de dicho esquema puedan realizar los test de forma más fácil. Se recomienda solo hacer test a lo usado ya que este API es auto generado y probablemente muchos endpoint no se usen.

**Comment by miguelramirez93** [comment]
tarea finalizada @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Tarea finalizada 

Proceeding to close Issue 👾
