### ISSUE TITLE
Actualización Pruebas unitarias

### ISSUE THREAD

**Issue by NeiderFajardo** [udistrital/necesidades_crud#33]
Se complementan las pruebas unitarias realizadas en #19 extendiendolas para cada uno de los esquemas de necesidades_crud.
No se pueden ejecutar de forma existosa debido a un error de conexión con la base de datos:

![image](https://user-images.githubusercontent.com/22989456/72455151-40c9b280-3790-11ea-93b0-c4768ee650df.png)

Se informa del tema al lider técnico @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Asociado al [Issue #49](https://github.com/udistrital/financiera_documentacion/issues/49)

**Comment by Soulfilip-UD** [comment]
Se realizan las pruebas unitarias y estás corren en local sin problemas, para finalizar la integración se requiere finalizar las tareas en el [Issue #35](https://github.com/udistrital/cuentas_contables_crud/issues/35) teniendo en cuenta que requiere una bd  de postgress.

Tarea finalizada 
Proceeding to close Issue 👾
